@echo off
set NAMESHARES_ROOT=%~dp0..\
echo Using %NAMESHARES_ROOT% as NameShares root directory

set OPENSSL_ROOT=%NAMESHARES_ROOT%\OpenSSL.x64
set OPENSSL_ROOT_DIR=%OPENSSL_ROOT%
set OPENSSL_INCLUDE_DIR=%OPENSSL_ROOT%\include
set DBROOTDIR=%NAMESHARES_ROOT%\BerkeleyDB.x64
set QTDIR=%NAMESHARES_ROOT%\QT.x64
set ICUROOT=%NAMESHARES_ROOT%\ICU.x64
set BOOST_ROOT=%NAMESHARES_ROOT%\boost_1.55.x64
set TCL_ROOT=%NAMESHARES_ROOT%\tcl.x64
set NPM_INSTALL_PREFIX=%NAMESHARES_ROOT%\npm

set PATH=%NPM_INSTALL_PREFIX%;"%APPDATA%"\npm;%QTDIR%\bin;%ICUROOT%\bin;%ICUROOT%\lib;%NAMESHARES_ROOT%\bin;%TCL_ROOT%\bin;%NAMESHARES_ROOT%\Cmake\bin;%BOOST_ROOT%\stage\lib;%PATH%
set CMAKE_PREFIX_PATH=%QTDIR%
set QT_QPA_PLATFORM_PLUGIN_PATH=%QTDIR%\plugins\platforms

echo Setting up VS2013 environment...
call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64
